import { Dish } from './dish';
export interface CompoundDish {
    id: number;
    userId: number;
    name: string;
    userName: string;
    fullname: string;
    email: string;
    calories: number;
    carbohydrates: number;
    proteins: number;
    fat: number;
    cholesterol: number;
    fiber: number;
    calcium: number;
    phosphorus: number;
    iron: number;
    potassium: number;
    sodium: number;
    zinc: number;
    magnesium: number;
    ribofla: number;
    niacin: number;
    folicAcid: number;
    vitaminA: number;
    vitaminC: number;
    vitaminB6: number;
    vitaminB12: number;
    thiamine: number;
    image: string;
    imageMimeType: string;
    createdAt: Date;
    modifiedAt: Date;
    dishCompoundDishResponse: Dish[];
    isAdminReviewed: boolean;
    isAdminConverted: boolean;
}