import { Tag } from './tag';

export interface Dish {
    id: number;
    name: string;
    nameEN: string;
    nameIT: string;
    calories: number;
    carbohydrates: number;
    proteins: number;
    fat: number;
    cholesterol: number;
    fiber: number;
    calcium: number;
    phosphorus: number;
    iron: number;
    potassium: number;
    sodium: number;
    zinc: number;
    vitaminB2Riboflavin: number;
    vitaminB3Niacin: number;
    vitaminA: number;
    vitaminC: number;
    vitaminB6: number;
    vitaminB12: number;
    vitaminD: number;
    vitaminE: number;
    vitaminK: number;
    vitaminB9Folate: number;
    vitaminB1Thiamin: number;
    image: string;
    imageMimeType: string;
    tags: Tag[];
    isProteic: boolean;
    isCaloric: boolean;
    isFruitAndVegetables: boolean;
    netWeight: number;
    volume: number;
    saturatedFat: number;
    monoUnsaturatedFat: number;
    polyUnsaturatedFat: number;
}
