export const Constants = {
  CONFIRM_URL: 'users/confirm/',
  RESEND_EMAIL_URL: 'users/resendConfirmation',
  GET_USER_URL: 'users/',
  UPDATED_USER_URL: 'users/',
  GET_STRATEGY_PERFORMANCE_URL: 'strategies/performance',
  GET_LAST_POSITIONS_URL: 'strategies/lastPositions',
  GET_ACCOUNT_URL: 'accounts/',
  SIGNIN_URL: 'auth/login',
  REGISTER_URL: 'users/',
  GET_PARAMETERS_URL: 'settings/',
  GET_SETTINGS_BY_USER_URL: 'users/settings/',
  UPDATED_SETTINGS_BY_USER_URL: 'users/settings/',
  GET_BROKERS_BY_USER_URL: 'users/brokers/',
  POST_BROKER_BY_USER_URL: 'users/brokers/',
  UPDATED_BROKER_SETTINGS_BY_USER_URL: 'users/brokers/',
  UPDATED_BROKER_EPICS_BY_USER_URL: 'users/epics/',
  POST_BROKER_EPIC_BY_USER_URL: 'users/epics/',
  DELETE_BROKER_EPIC_BY_USER_URL: 'users/epics/',
  GET_BROKERS: 'brokers/',
  GET_EPICS_BY_BROKER_URL: 'brokers/epics/',
  GET_GENERAL_PARAMETERS_URL: 'generalSettings/',
  UPDATED_GENERAL_PARAMETERS_URL: 'generalSettings/',
  POST_START_TRADING: 'users/startTrade/',
  GET_USER_IS_TRADING: 'users/isTrading/',
  POST_STOP_TRADING: 'users/stopTrade/',
  CREDENTIALS_KEY: 'credentials'
};
